#Final Project 
# Akshat, David, and Fabliha

-- MySQL Script generated by MySQL Workbench
-- Tue Nov 20 12:21:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema akshatpatel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema akshatpatel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `akshatpatel` DEFAULT CHARACTER SET utf8 ;
USE `akshatpatel` ;

-- -----------------------------------------------------
-- Table `akshatpatel`.`Incident`
-- -----------------------------------------------------
DROP TABLE Incident;
CREATE TABLE IF NOT EXISTS `akshatpatel`.`Incident` (
  `incidentID` INT NOT NULL,
  `typeOfIncident` VARCHAR(45) NULL,
  `dateCreated` DATE NULL,
  `incidentState` VARCHAR(45) NULL,
  `User_incidentID` INT NULL,
  PRIMARY KEY (`incidentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akshatpatel`.`User`
-- -----------------------------------------------------
DROP TABLE `User`;
CREATE TABLE IF NOT EXISTS `akshatpatel`.`User` (
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `jobTitle` VARCHAR(45) NULL,
  `emailAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`lastName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akshatpatel`.`comment`
-- -----------------------------------------------------
DROP TABLE `comment`; 
CREATE TABLE IF NOT EXISTS `akshatpatel`.`comment` (
  `comments` VARCHAR(100) NOT NULL,
  `Incident_incidentID` INT NOT NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`comments`, `Incident_incidentID`),
  INDEX `fk_DescriptionOfIncident_Incident1_idx` (`Incident_incidentID` ASC) VISIBLE,
  CONSTRAINT `fk_DescriptionOfIncident_Incident1`
    FOREIGN KEY (`Incident_incidentID`)
    REFERENCES `akshatpatel`.`Incident` (`incidentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akshatpatel`.`User_has_Incident`
-- -----------------------------------------------------
DROP TABLE User_has_Incident;
CREATE TABLE IF NOT EXISTS `akshatpatel`.`User_has_Incident` (
  `User_lastName` VARCHAR(45) NOT NULL,
  `Incident_incidentID` INT NOT NULL,
  PRIMARY KEY (`User_lastName`, `Incident_incidentID`),
  INDEX `fk_User_has_Incident_Incident1_idx` (`Incident_incidentID` ASC) VISIBLE,
  INDEX `fk_User_has_Incident_User1_idx` (`User_lastName` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Incident_User1`
    FOREIGN KEY (`User_lastName`)
    REFERENCES `akshatpatel`.`User` (`lastName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Incident_Incident1`
    FOREIGN KEY (`Incident_incidentID`)
    REFERENCES `akshatpatel`.`Incident` (`incidentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akshatpatel`.`IP_Address`
-- -----------------------------------------------------
DROP TABLE IP_Address; 
CREATE TABLE IF NOT EXISTS `akshatpatel`.`IP_Address` (
  `ipAddress` VARCHAR(18) NOT NULL,
  `Incident_incidentID` INT NOT NULL,
  PRIMARY KEY (`ipAddress`, `Incident_incidentID`),
  INDEX `fk_IP_Address_Incident1_idx` (`Incident_incidentID` ASC) VISIBLE,
  CONSTRAINT `fk_IP_Address_Incident1`
    FOREIGN KEY (`Incident_incidentID`)
    REFERENCES `akshatpatel`.`Incident` (`incidentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


#SET SQL_MODE=@OLD_SQL_MODE;
#SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
#SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;